name: Continuous integration (CI)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  npm-install-and-lint:
    name: NPM Install and Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

  cypress-e2e-test:
    name: Cypress End to End Testing
    runs-on: ubuntu-22.04
    needs: npm-install-and-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run cy:e2e

  docker-build:
    name: Build docker image and publish
    runs-on: ubuntu-22.04
    needs: npm-install-and-lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/college-system:latest
