name: NPM Install and Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  npm-install-and-lint:
    name: NPM Install and Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint
